### PR TITLE
Swatitayal

### PR DESCRIPTION
**Pull request by swatitayal**
Disabled "Previous Page" link on pagination bar

### CODE REVIEW

**Review by AndrewPBartson — COMMENTED** [review]
Hi Swati
   I have a question about line 17 in _pagination.cshtml:
   <a class="esh-pager-item esh-pager-item--navigable pager_item @Model.Previous"
   
   I don't know what the "@Model.Previous" is doing. Maybe you can clarify?

**Comment by swatitayal** [comment]
> Hi Swati I have a question about line 17 in _pagination.cshtml: <a class="esh-pager-item esh-pager-item--navigable pager_item @Model.Previous"
> 
> I don't know what the "@Model.Previous" is doing. Maybe you can clarify?

So, there is a pager.css file in WebMvc>wwwroot>css>shared>pager that defines certain formatting styles. Kal have used to same code for Next button.

@Model.Previous refers to the "Previous" property of the "PaginationInfo" class that we are using as model here.

**Review by AndrewPBartson — APPROVED** [review]
The string "@Model.Previous" on line 17 in _pagination.cshtml came along with Kal's Jewels project. I don't understand this code but it might be important so I suggest just leave as is.  For the rest of the code, I don't have questions and it seems good to go.

**Comment by swatitayal** [comment]
Thanks Andrew!

**Pull request merged**
